### PR TITLE
Respect show pre-release setting on initial installation

### LINKED ISSUE #737: Initial installation does not respect `pre-release` settings
I enabled `Include Prerelease Versions` settings in rancher preferences.

Initial installation of `kubewarden-controller` does not respect this setting. 
It redirects me to installation of `stable` version and UI offers upgrade afterwards.

### PR DESCRIPTION
**Pull request by jordojordo**
Fix #737 

This will add the ability to install pre-release charts when installing the Kubewarden Controller.

https://github.com/rancher/kubewarden-ui/assets/40806497/dd232a2f-260e-4a4b-a9ef-a5838a53c098

### CODE REVIEW

**Comment by kravciak** [comment]
It works fine but I found one issue about policy-server which defaults to stable version, which might not be complatible:

[Screencast from 2024-06-25 11-48-02.webm](https://github.com/rancher/kubewarden-ui/assets/538604/ea4e4487-2288-45f2-b443-4aadf9585970)

**Comment by jordojordo** [comment]
@kravciak This should be fixed now, the policy server detail page wasn't respecting the pre-release setting.

**Comment by kravciak** [comment]
I tested on rancher-prime v2.8.5 and I always get `latest` policy server - for both released & pre-release setting.

I also see error about `rancher-charts?...&version=undefined` in console log

```log        
GET https://172.25.0.2.nip.io/v1/catalog.cattle.io.clusterrepos/kubewarden-charts?link=info&chartName=kubewarden-defaults&version=undefined 500 (Internal Server Error)

fetch.client.js:79 Error in fetch(): {type: 'error', links: {…}, code: 'ServerError', message: 'improper constraint: undefined', status: 500, …}
```

**Comment by kravciak** [comment]
I tried latest version and found one more issue.

I have older cluster with versions: `app: 1.11.0`, `controller: 2.0.10`, `defaults: 1.9.4`.
Installed chart creates default policy-server `v1.11.0`. But when I create one manually it uses image 1.14.0 (last released).

Policy server chart version does not take into account older kw stack version compatibility.

**Comment by jordojordo** [comment]
>Policy server chart version does not take into account older kw stack version compatibility.

This was an existing issue, we were not determining the latest compatible version for the policy server when manually creating one.

**Comment by kravciak** [comment]
> This was an existing issue, we were not determining the latest compatible version for the policy server when manually creating one.

LGTM then

**Review by kravciak — APPROVED** [review]

**Pull request merged**
