### PR TITLE
Fix tracing checklist Update Config button link

### LINKED ISSUE #529: Tracing `Update Chart` button can't be clicked
rancher: v2.8.0-rc3, 2.7.9
kw extension: head

[Screencast from 2023-10-26 23-21-09.webm](https://github.com/rancher/kubewarden-ui/assets/538604/31271c4b-0025-4f43-b4e2-a8a5ea1a437e)

### PR DESCRIPTION
**Pull request by jordojordo**
Fix #529 

This fixes the Tracing Checklist link to update the kubewarden-controller chart by passing in the controller's app resource instead of the chart. Also updated the wording from "Update Chart" to "Update Config" to be consistent with the Metrics Checklist.

https://github.com/rancher/kubewarden-ui/assets/40806497/eb0887b2-ec70-4221-924b-136febf29bd9

### CODE REVIEW

**Comment by kravciak** [comment]
Tracing page does not detect that tracing is enabled, it always shows `Update Config` button.

[Screencast from 2023-10-29 18-27-18.webm](https://github.com/rancher/kubewarden-ui/assets/538604/d094ca69-77fd-4b48-8cef-37071198bb5b)

**Comment by jordojordo** [comment]
This should be fixed, I was previously checking the controller chart rather than the controller app resource.


https://github.com/rancher/kubewarden-ui/assets/40806497/e8a730cf-d333-4016-85f3-0efad7ca33ef

**Comment by jordojordo** [comment]
The e2e tests are failing since [this commit](https://github.com/rancher/kubewarden-ui/pull/533) was reverted. The wording for the save button has changed but will not be reflected in other tests until 1.3.0 is released.

**Review by kravciak — APPROVED** [review]
I tested it with https://github.com/rancher/kubewarden-ui/pull/523 - works fine now.

**Pull request merged**
