### PR TITLE
Fix resource fetching when user lacks permission

### LINKED ISSUE #774: [Bug] Kubewarden side menu item visible to users without permissions
Users that do not have permissions to manage Kubewarden resources are able to navigate to the Kubewarden dashboard page. They will not see any of the installed resources, instead they will be prompted with the Installation wizard.

The Kubewarden menu item should be removed for users who do not have access to the kw resources.

### PR DESCRIPTION
**Pull request by jordojordo**
Fix #774 

This will limit the ability to use the Kubewarden extension to users who do not have the proper permissions. There are many pages/components that fetch resources that will now be gated depending on the user's permission level.

The Dashboard page will now display a banner explaining this change when a user does not have access to all of the following types or they are an administrator:
- `policies.kubewarden.io.policyservers`
- `policies.kubewarden.io.clusteradmissionpolicies`
- `policies.kubewarden.io.admissionpolicies`
- `catalog.cattle.io.apps`
- `apps.deployments`

__User with no permissions__

user-has-nothing

__User has policy server permissions__

user-has-ps

__User has both policy type permissions__

user-has-policies

There is no elegant solution to not showing the entire Kubewarden extension to users that do not have access to Kubewarden types as the Dashboard page will always show. Since the dashboard is considered a `virtualType` and it is not tied to a Schema, we are limited in the way we can choose to display this menu item. There will need to be a change on the `@rancher/dashboard` side to fix this.

### CODE REVIEW

**Comment by kravciak** [comment]
I see 3 default user types: User-Base, Standard User, Administrator.
I created Standard User (no additional permissions) to test with.

- As standard user I imported cluster (TUR) to Rancher
- As standard user I was not able to install Kubewarden. (You do not have access to the Kubewarden Dashboard...)
- As administrator I installed Kubewarden on TUR cluster
- As standard user I am able to use Kubewarden but I can't access Kubewarden Dashboard

[Screencast from 2024-07-12 10-26-57.webm](https://github.com/user-attachments/assets/5a575b02-32b0-495a-8abb-cf3d0589c785)

**Comment by kravciak** [comment]
> @kravciak I'm not able to control any Kubewarden resources as a standard user without additional permissions, is this behavior only possible in Prime?

This happens if user has `Cluster Owner` role.

**Comment by jordojordo** [comment]
I'm not seeing that behavior with a Cluster Owner as well. What permissions do your Cluster Owners have?

**Comment by kravciak** [comment]
We found out that bug is present when user does not have permissions on local cluster.

**Comment by jordojordo** [comment]
@kravciak The issue was using provided methods within the `@rancher/shell` package for `isAdminUser` and `checkPermissions`. These were both checking for schemas on the management (Rancher cluster) level, not per cluster.

A standard user who is a cluster owner should be able to view the dashboard now.

**Review by kravciak — APPROVED** [review]
Works fine now. I can't whitelist artifacthub as standard user, but I think that's by design or not related to this PR. Approving.

[Screencast from 2024-07-15 09-49-29.webm](https://github.com/user-attachments/assets/38a6305e-0c44-4609-ac99-0bab9324a6e8)

**Pull request merged**
