### PR TITLE
Fix fetching of policy server schema resourceFields

### LINKED ISSUE #791: [Bug] Cannot find `resourceFields` for schema `policies.kubewarden.io.policyserver`
When running the extension on Rancher `v2.9-head` (`v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head`), this error appears in the console when attempting to create/edit a Policy Server:

```
Error: Cannot find resourceFields for Schema policies.kubewarden.io.policyserver (schemaDefinitions have not been fetched) 
    get steve-schema.ts:103
    h create-yaml.js:134
    f create-yaml.js:73
    createResourceYaml CruResource.vue:322
```

This causes a blank screen to appear.

### PR DESCRIPTION
**Pull request by jordojordo**
Fix #791 

There are some changes within the `rancher/shell` package that caused some issues with the PolicyServer schema fetching. This PR has a few changes to fix this:

- Bumped the `@rancher/shell` package to `2.0.1`
- Manually fetch resource fields with `schema.fetchResourceFields()`
- Pinned the `catalog.cattle.io/rancher-version` annotation to `>= 2.9.0-0`
- Pinned the `catalog.cattle.io/ui-extension-version` annotation to `>= 2.0.0`

### CODE REVIEW

**Comment by kravciak** [comment]
It fixes issues with 2.9, I found only one problem:

[Screencast from 2024-07-16 17-45-07.webm](https://github.com/user-attachments/assets/65623802-03b4-4def-b864-2317af64fe73)

**Review by aalves08 — APPROVED** [review]
codewise, LGTM mate!

**Comment by jordojordo** [comment]
@kravciak That seems like an issue that existed prior to these changes and should be fixed in a separate PR

**Review by kravciak — APPROVED** [review]

**Comment by kravciak** [comment]
> @kravciak That seems like an issue that existed prior to these changes and should be fixed in a separate PR

Bug is not present on currently v1.6.2 (rancher 2.8.5), that's why I thought it was introduced by this PR.
I created https://github.com/rancher/kubewarden-ui/issues/803.

**Comment by kravciak** [comment]
Btw this PR breaks compatibility with rancher 2.7 and 2.8, right?

**Comment by jordojordo** [comment]
I could see the bug without these code changes on 2.9, so I assume this is a consequence of some changes on the dashboard side.

> Btw this PR breaks compatibility with rancher 2.7 and 2.8, right?

Correct.

**Pull request merged**
