### PR TITLE
[Backport] fix tracing and metrics controller app check

### PR DESCRIPTION
**Pull request by jordojordo**
Backport of dae0ff1012463d211447049b4456e339cf0aeebb

Bump `@rancher/shell` to version `2.0.2`

### CODE REVIEW

**Comment by kravciak** [comment]
https://github.com/user-attachments/assets/76210dfd-210f-4270-a97b-3e95991c3661

**Comment by jordojordo** [comment]
@kravciak Try again with the updated rancher/shell package.

**Comment by kravciak** [comment]
It seems it didn't help.

**Comment by jordojordo** [comment]
I'm not seeing this behavior, can you ensure your node_modules were deleted before reinstalling and the yarn cache is cleared?

**Comment by kravciak** [comment]
I tried that but result is the same - I am trying it on rancher v2.9.4-alpha3.

**Comment by jordojordo** [comment]
I've moved the `fetchValues` method call to happen anytime the `controllerApp` property is updated, this should fix the issue of fetchValues not being called.

**Review by kravciak — APPROVED** [review]

**Pull request merged**
